---
version: "2.3"
services:
  sonarr: # tv series collection manager
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - ./apps/sonarr/config:/config # config files
      - ${ROOT}/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr: # movies colection manager
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - ./apps/radarr/config:/config
      - ${ROOT}/movies:/movies #optional
      - ${ROOT}/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  lidarr: # music collection manager
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - ./apps/lidarr/config:/config
      - ${ROOT}/music:/music #optional
      - ${ROOT}/downloads:/downloads #optional
      - ./apps/lidarr/custom-services.d:/custom-services.d #scripts by RandomNinjaAtk
      - ./apps/lidarr/custom-cont-init.d:/custom-cont-init.d #scripts by RandomNinjaAtk
    ports:
      - 8686:8686
    restart: unless-stopped

  readarr: # ebook collection manager
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - ./apps/readarr/config:/config
      - ${ROOT}/ebooks:/books #optional
      - ${ROOT}/downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped

  whisparr: # adult movie collection manager
    image: cr.hotio.dev/hotio/whisparr
    container_name: whisparr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      #- UMASK=002
    ports:
      - 6969:6969
    volumes:
      - ./apps/whisparr/config:/config

  mylar3: # comic book collection manager
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ./apps/mylar3/config:/config
      - ${ROOT}/comics:/comics
      - ${ROOT}/downloads:/downloads
    ports:
      - 8090:8090
    restart: unless-stopped

  lazylibrarian: #ebooks, audiobooks and magazines manager
    image: lscr.io/linuxserver/lazylibrarian:latest
    container_name: lazylibrarian
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - DOCKER_MODS=linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - ./apps/lazylibrarian/config:/config
      - ${ROOT}/ebooks:/books
      - ${ROOT}/downloads:/downloads
    ports:
      - 5299:5299
    restart: unless-stopped

  bazarr: #subtitle for movie and tv
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - ./apps/bazarr/config:/config
      - ${ROOT}/movies:/movies #optional
      - ${ROOT}/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

  prowlarr: # indexer for tv, movie, music, ebook
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - ./apps/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  qbittorrent: # torrent client
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - WEBUI_PORT=8082
    volumes:
      - ./apps/qbittorrent/config:/config
      - ${ROOT}/downloads:/downloads
    ports:
      - 8082:8082
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ./apps/jellyfin/config:/config
      - ${ROOT}/tv:/data/tvshows
      - ${ROOT}/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  autobrr: #download automation tool for torrents and usenet, with IRC announces
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    user: ${PUID}:${PGID}
    volumes:
      - ./apps/autobrr/config:/config
    ports:
      - 7474:7474

  stash: # video and image organizer
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ports:
      - "9999:9999"
    ## If you intend to use stash's DLNA functionality uncomment the below network mode and comment out the above ports section
    # network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999 #should change with routed 9999 port
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./apps/stash/config:/root/.stash
      - ./apps/stash/data:/data
      - ./apps/stash/metadata:/metadata
      - ./apps/stash/cache:/cache
      - ./apps/stash/blobs:/blobs
      - ./apps/stash/generated:/generated

  komga: # media server for your comics, mangas, BDs and magazines.
    image: gotson/komga
    container_name: komga
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ./apps/komga/config:/config
      - ${ROOT}/comics:/data
    ports:
      - 25600:25600
    restart: unless-stopped    

  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - ${ROOT}/downloads:/downloads
    restart: unless-stopped    
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
      # General config
      - UN_DEBUG=false
      - UN_LOG_FILE=
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      # Sonarr Config
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=c7f30e75f47949488b33dedb1275247a
      - UN_SONARR_0_PATHS_0=/downloads
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_DELETE_ORIG=false
      - UN_SONARR_0_DELETE_DELAY=5m
      # Radarr Config
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=ea6ee52fd3474e1398b7f3365304e258
      - UN_RADARR_0_PATHS_0=/downloads
      - UN_RADARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_DELETE_ORIG=false
      - UN_RADARR_0_DELETE_DELAY=5m
      # Lidarr Config
      - UN_LIDARR_0_URL=http://lidarr:8686
      - UN_LIDARR_0_API_KEY=4cf5d57bcdbe40c89488bbc959f3710a
      - UN_LIDARR_0_PATHS_0=/downloads
      - UN_LIDARR_0_PROTOCOLS=torrent
      - UN_LIDARR_0_TIMEOUT=10s
      - UN_LIDARR_0_DELETE_ORIG=false
      - UN_LIDARR_0_DELETE_DELAY=5m
      # Readarr Config
      - UN_READARR_0_URL=http://readarr:8787
      - UN_READARR_0_API_KEY=11f68f6b64d94f58ab57e4ca14c03a2d
      - UN_READARR_0_PATHS_0=/downloads
      - UN_READARR_0_PROTOCOLS=torrent
      - UN_READARR_0_TIMEOUT=10s
      - UN_READARR_0_DELETE_ORIG=false
      - UN_READARR_0_DELETE_DELAY=5m
    security_opt:
      - no-new-privileges:true

  # omegabrr: # transforms items monitored by arrs or lists into autobrr filters. Useful for automating your filters for monitored media or racing criteria.
  #   container_name: omegabrr
  #   image: ghcr.io/autobrr/omegabrr:latest
  #   environment:
  #     - TZ=${TZ}
  #   user: ${PUID}:${PGID}
  #   ports:
  #     - "7441:7441"
  #   volumes:
  #     - "./apps/omegabrr/config:/config"
  #   restart: unless-stopped
