---
version: "2.1"
services:
  sonarr: # tv series collection manager
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
    volumes:
      - ./apps/sonarr/config:/config
      - ./media/tv:/tv #optional
      - ./media/torrent:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr: # movies colection manager
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
    volumes:
      - ./apps/radarr/config:/config
      - ./media/movie:/movies #optional
      - ./media/torrent:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  lidarr: # music collection manager
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
    volumes:
      - ./apps/lidar/config:/config
      - ./media/music:/music #optional
      - ./media/torrent:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped

  readarr: # ebook collection manager
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Brazil
    volumes:
      - ./apps/readarr/config:/config
      - ./media/ebook:/books #optional
      - ./media/torrent:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped

  bazarr: #subtitle for movie and tv
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./apps/bazarr/config:/config
      - ./media/movie:/movies #optional
      - ./media/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

  jackett: # indexer for tv, movie, music, ebook
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ./apps/jackett/config:/config
      - ./media/torrent:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  qbittorrent: # torrent client
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
      - WEBUI_PORT=8082
    volumes:
      - ./apps/qbittorrent/config:/config
      - ./media/torrent:/downloads
    ports:
      - 8082:8082
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Brazil
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ./apps/jellyfin/config:/config
      - ./media/tv:/data/tvshows
      - ./media/movie:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
