---
version: "2.3"
services:
  sonarr: # tv series collection manager
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - ./apps/sonarr/config:/config # config files
      - ${ROOT}/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr: # movies colection manager
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - ./apps/radarr/config:/config
      - ${ROOT}/movies:/movies #optional
      - ${ROOT}/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  lidarr: # music collection manager
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - ./apps/lidar/config:/config
      - ${ROOT}/music:/music #optional
      - ${ROOT}/downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped

  readarr: # ebook collection manager
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - ./apps/readarr/config:/config
      - ${ROOT}/ebooks:/books #optional
      - ${ROOT}/downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped

  bazarr: #subtitle for movie and tv
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - ./apps/bazarr/config:/config
      - ${ROOT}/movies:/movies #optional
      - ${ROOT}/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

  prowlarr: # indexer for tv, movie, music, ebook
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - ./apps/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  qbittorrent: # torrent client
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - WEBUI_PORT=8082
    volumes:
      - ./apps/qbittorrent/config:/config
      - ${ROOT}/downloads:/downloads
    ports:
      - 8082:8082
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ./apps/jellyfin/config:/config
      - ${ROOT}/tv:/data/tvshows
      - ${ROOT}/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
